// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.nfctag.domain;

import org.esupportail.nfctag.domain.Device;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Device_Roo_Configurable {
    
    declare @type: Device: @Configurable;
    
}
