// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.nfctag.service.api.impl;

import org.esupportail.nfctag.service.api.impl.DesfireReadDeuinfoConfig;
import org.slf4j.Logger;

privileged aspect DesfireReadDeuinfoConfig_Roo_JavaBean {
    
    public Logger DesfireReadDeuinfoConfig.getLog() {
        return this.log;
    }
    
}
